html markups for index.html and catalog.html
htmlacademy-htmlcss/2205907-sedona-35 pull request #2
Opened 2022-09-25 14:02 UTC by yunussovd

2022-09-25 14:42 UTC, Dima-Dim requested changes
https://up.htmlacademy.ru/htmlcss/35/criteries#PROJ-03 ну и на странице задания указано что в рамках этого задания нужна только разметка. Оставь, пожалуйста, здесь только её.

2022-09-25 15:05 UTC, yunussovd commented
Критерий выполнил, дело было в дефисах и подчеркиваниях, как я понял, а по второму пункту, убрать css файл из реквеста или из своего репозитория пока что?

2022-09-26 01:33 UTC, Dima-Dim commented
> Критерий выполнил, дело было в дефисах и подчеркиваниях, как я понял, а по второму пункту, убрать css файл из реквеста или из своего репозитория пока что?

По 1-ому пункту и в пробелах и в больших буквах :) которые всё ещё есть в репозитории. В разметке тоже не нужно писать слова большими буквами, если это не абривиатуры, которые всегда только так и пишутся. Стилизация будет производиться с помощью CSS далее по программе.
По 2-ому как тебе удобнее, но в пуллриквесте должна быть только разметка.

2022-09-26 03:17 UTC, yunussovd commented
По названиям в разметке, кстати, сомневался, сегодня уберу капсы все и css из реквеста

2022-09-26 04:29 UTC, yunussovd commented
Готово, оставил капс только на первую букву в названиях,  сss вырезал, могу второй раз пулл реквест создавать?

2022-09-27 01:36 UTC, Dima-Dim commented
> Готово, оставил капс только на первую букву в названиях, сss вырезал, могу второй раз пулл реквест создавать?

Пуллриквест уже открыть, второй делать не нужно. Достаточно отправить изменения в репозиторий и отправить задание на проверку.

2022-09-27 03:21 UTC, yunussovd commented
Думаю, все правильно сделал

2022-09-27 03:25 UTC, Dima-Dim commented
> Думаю, все правильно сделал

Я всё ещё вижу файла, в назаниях которых есть большие буквы, например, [HTMLAcademy.png](https://github.com/htmlacademy-htmlcss/2205907-sedona-35/pull/2/files#diff-e78caa9b047f30e11e30270610a0121f44bf7db88096c167122c0918fc1fa999) и пробелы, например, [search (1).png](https://github.com/htmlacademy-htmlcss/2205907-sedona-35/pull/2/files#diff-edc9640975e09e836a0a0f28bc3395c45310a4c933b642829ffc92de49eea283)

2022-09-27 03:35 UTC, yunussovd commented
А, в папке images увидел

2022-09-27 03:38 UTC, yunussovd commented
Вроде все исправил

2022-09-27 03:41 UTC, yunussovd commented
Название картинки у меня маленькими буквами , в репозитории большими почему-то

2022-09-27 03:44 UTC, yunussovd commented
Извиняюсь, исправил название

2022-09-28 01:38 UTC, Dima-Dim requested changes

2022-09-28 01:38 UTC, Dima-Dim commented on catalog.html
> +    <meta charset="utf-8" />
`/` перед `>` не нужен. Нужно проверять что получилось в html файле с помощью validator.w3.org/nu/

2022-09-28 01:38 UTC, Dima-Dim commented on catalog.html
> +        <li class="controls-item"><button class="controls-button" type="button"><img src="images/searchicon1.png"
Именно из-за того что вы прошли пока только информацию для разметки, остальное делать не нужно. А данном случае это не контеное изображение и в разметку добавлять его не нужно. А вот написать что это поиск текстом, для доступности, стоит.

2022-09-28 01:38 UTC, Dima-Dim commented on catalog.html
> +          <li class="breadcrumbs-item"><a class="breadcrumbs-link" href="index.html"><img src=""
Тоже декоративное изображение, которого в разметке быть не должно.

2022-09-28 01:38 UTC, Dima-Dim commented on catalog.html
> +            <dl>
Использование `dl` здесь избыточно. Расположенный текст в одну строку и так даст понимание что к чему.

2022-09-28 01:38 UTC, Dima-Dim commented on catalog.html
> +        <img class="subscribe-background" src="images/subscribe-background.jpg" width="1200" height="414.86" alt="">
Тоже что-то лишнее, а вместе с ним возможно что и `div` тоже.

2022-09-28 01:38 UTC, Dima-Dim commented on catalog.html
> +        <div class="footer-social">
А чего не список?

2022-09-28 01:38 UTC, Dima-Dim commented on catalog.html
> +        <div class="foter-contacts-phone">
Зачем лишний `div`?

2022-09-28 01:38 UTC, Dima-Dim commented on index.html
> +          <img class="intro-img-welcome" src="images/welcome.png" width="187.7" height="44.7" alt="">
Слишком много изображений. Всё это можно логически объединить и максимум их тут будет 2.

2022-09-28 01:38 UTC, Dima-Dim commented on index.html
> +          <h2>Седона — небольшой городок в Аризоне,<br>
`br` это про стилизацию, её мы пока не делаем, потому что ещё не знаем как её делать правильно. `span` тут видимо про тоже.

2022-09-28 01:38 UTC, Dima-Dim commented on index.html
> +      <article class="title">
Так себе статья из 1-го заголовка и 1-го предложения.

2022-09-28 01:38 UTC, Dima-Dim commented on index.html
> +          <li class="advantages-img-city"><img src="images/city.jpg" width="800" height="384"
Изображение это не отдельный пункт списка.

2022-09-28 04:32 UTC, yunussovd commented on catalog.html
> +    <meta charset="utf-8" />
я и индекс и каталог на валидаторе проверял, исправлял ошибки и прочее, на это он не ругался,  исправил

2022-09-28 04:47 UTC, yunussovd commented on catalog.html
> +        <div class="footer-social">
Решил на блоки с дивом, сначала думал сделать все общим списком, но сложнее было эелементы в фетере расположить, а так три блока как и на макете, вот и пришел к диву

2022-09-28 04:48 UTC, yunussovd commented on catalog.html
> +        <div class="foter-contacts-phone">
он не лишний

2022-09-28 04:51 UTC, yunussovd commented on index.html
> +          <h2>Седона — небольшой городок в Аризоне,<br>
span в лайвах вставляли, а br я вставил чтобы текст перенести и плюс, в фигме были символы странные в местах переноса, вот и вставил br

2022-09-28 04:52 UTC, yunussovd commented on index.html
> +      <article class="title">
cделал секцией

2022-09-28 04:53 UTC, yunussovd commented on index.html
> +          <li class="advantages-img-city"><img src="images/city.jpg" width="800" height="384"
валидатор ругался, что если делаешь список, то он должен состоять из li, просто так вставить img между ними нельзя, вот я и обернул

2022-09-28 04:54 UTC, yunussovd commented on catalog.html
> +          <li class="breadcrumbs-item"><a class="breadcrumbs-link" href="index.html"><img src=""
пока все вставил, на неделе буду уже разбивать на декор и контент

2022-09-28 04:55 UTC, yunussovd commented on catalog.html
> +            <dl>
Исправил , dl убрал dt на p заменил, ориентировался на статью, там подобный вариант (гостиницы - - - цена) был сделан на dl dt, вот и решил что там будет корректнее

2022-09-28 04:56 UTC, yunussovd commented on catalog.html
> +        <img class="subscribe-background" src="images/subscribe-background.jpg" width="1200" height="414.86" alt="">
убрал див, картинку позже перенесу в сss под background-image

2022-09-28 04:56 UTC, yunussovd commented on index.html
> +          <img class="intro-img-welcome" src="images/welcome.png" width="187.7" height="44.7" alt="">
devider кинул в див intro-text

2022-09-28 05:03 UTC, Dima-Dim commented on catalog.html
> +        <div class="foter-contacts-phone">
Для чего он сейчас используется?

2022-09-28 05:03 UTC, Dima-Dim commented on index.html
> +          <h2>Седона — небольшой городок в Аризоне,<br>
Переносы это стилизация, сейчас мы делаем только разметку.

2022-09-28 05:06 UTC, Dima-Dim commented on index.html
> +          <li class="advantages-img-city"><img src="images/city.jpg" width="800" height="384"
И он совершенно правильно ругался, но просто обернуть лишнюю запчасть в отдельный li это не верное решение.

2022-09-28 07:49 UTC, yunussovd commented on catalog.html
> +        <div class="foter-contacts-phone">
там там блок соц сети, блок телефон, блок ссылка на академию, можно конечно сделать блок соц сети + номер + ссылка на академию ( без обертки в див последних двух)

2022-09-28 07:51 UTC, yunussovd commented on index.html
> +          <h2>Седона — небольшой городок в Аризоне,<br>
убрал все br

2022-09-28 07:56 UTC, yunussovd commented on index.html
> +          <li class="advantages-img-city"><img src="images/city.jpg" width="800" height="384"
вытащил img из li, и вставил после /ul clas="advantages-list"

2022-09-29 06:28 UTC, Dima-Dim commented on index.html
> +          <li class="advantages-img-city"><img src="images/city.jpg" width="800" height="384"
Т.е. ты считаешь что эти изображения всё же сами по себе и не относятся ни к одному пункту из списка?

2022-09-29 09:48 UTC, yunussovd commented on index.html
> +          <li class="advantages-img-city"><img src="images/city.jpg" width="800" height="384"
а, понял, они же к тексту относятся,  я изначально их писал как каждый отдельный li, чтобы на гридах легче было секцию стилизовать, но по сути они должны быть рядом с текстом, но каждый li  - это блок у меня, поэтому я в верстку заглядывал уже, удобно будет или нет потом к ним обращаться из css
Сейчас исправлю и положу img  в li  с подходящим текстом

2022-09-29 11:59 UTC, Dima-Dim commented on index.html
> +          <li class="advantages-img-city"><img src="images/city.jpg" width="800" height="384"
Сейчас мы не делаем стилизацию и думаем только о семантичной разметки :)

2022-09-29 13:39 UTC, yunussovd commented on index.html
> +          <li class="advantages-img-city"><img src="images/city.jpg" width="800" height="384"
Готовлю почву, так сказать, чтобы и разметка норм была, и чтобы потом проще было стилизацию делать) 
что еще исправить, чтобы разметку сдать?

2022-09-29 13:48 UTC, yunussovd commented on index.html
> +          <li class="advantages-img-city"><img src="images/city.jpg" width="800" height="384"
я еще чутка в пулл реквест картинки начал добавлять

2022-09-29 13:54 UTC, Dima-Dim commented on index.html
> +          <li class="advantages-img-city"><img src="images/city.jpg" width="800" height="384"
Не нужно добавлять то, что не нужно добавлять в рамках задания для которого пуллриквесет.

2022-09-29 14:25 UTC, yunussovd commented on index.html
> +          <li class="advantages-img-city"><img src="images/city.jpg" width="800" height="384"
блин, если честно ожидал, что не пойдет сюда, но смотрю коммиты в рамках этого  реквеста добавляются все, давайте, я сегодня еще добью разметку, она сейчас чутка изменится, во всяком случае, я декоративные элементы убираю
Потом в свой репозиторий все толкну и завтра уже глянем и надеюсь, там все нормально будет

2022-09-29 14:36 UTC, yunussovd commented on index.html
> +          <li class="advantages-img-city"><img src="images/city.jpg" width="800" height="384"
Готово, весь декор убрал, разметка немного изменилась, после этого пулл реквеста, создам пулл уже на графику , но это уже совсем другая история)

2022-09-30 03:33 UTC, Dima-Dim commented on index.html
> +          <li class="advantages-img-city"><img src="images/city.jpg" width="800" height="384"
Не рекомендовал бы делать пуллриквесеты если не принят текущий.

2022-09-30 03:44 UTC, Dima-Dim requested changes
Валидаор всё ещё указывает на большое количество варнингов которые не сложно исправить.

2022-09-30 03:44 UTC, Dima-Dim commented on catalog.html
> +        <div class="foter-contacts-phone">
Где там? В этом div-е только ссылка. Зачем этой ссылке дополнительная обёртка? :)

2022-09-30 03:44 UTC, Dima-Dim commented on catalog.html
> +        <div class="footer-contacts-htmlacademy"><a class="footer-count-link" href="https://htmlacademy.ru/"><img
Так же как и тут зачем ссылке обёртка?

2022-09-30 03:44 UTC, Dima-Dim commented on index.html
> +          <li class="navigation-item "><a class="navigation-link navigation-link-current" href="index.html">Главная</a>
Когда ты смотришь на такой код насколько тебе бысто и удобно понимать что тут во что вложено и вложено ли вообще? Не лучше бы было переносить вложенный тег на новую строку?

2022-09-30 03:44 UTC, Dima-Dim commented on index.html
> +        <h2 class="visually-hidden">Введение</h2>
Очень не однозначный заголовок :) Естьт же вон более разумный h1, может лучше использовать тут его?

2022-09-30 03:44 UTC, Dima-Dim commented on index.html
> +            <img src="images/advantage-house.svg" width="75" height="72" alt="">
Декоративное изображение.

2022-09-30 03:44 UTC, Dima-Dim commented on index.html
> +        <div class="footer-social">
Чего всё ещё  не список?

2022-09-30 03:49 UTC, Dima-Dim commented on index.html
> +          <li class="advantages-img-city"><img src="images/city.jpg" width="800" height="384"
И если готово, то не забывай отправлять задание на провеку. Сейчас проверил без этого, так отправляй уже после внесения правок.

2022-09-30 04:51 UTC, yunussovd commented on index.html
> +        <div class="footer-social">
Cделал  списком все ссылки из футера

2022-09-30 04:51 UTC, yunussovd commented on index.html
> +            <img src="images/advantage-house.svg" width="75" height="72" alt="">
Убрал все 3 декор картинки из блока

2022-09-30 04:52 UTC, yunussovd commented on index.html
> +        <h2 class="visually-hidden">Введение</h2>
текст с h1 вставил в h2 вместо слова Введение

2022-09-30 05:08 UTC, yunussovd commented on index.html
> +          <li class="navigation-item "><a class="navigation-link navigation-link-current" href="index.html">Главная</a>
Cделал комит, исправления валидатора на индекс файл только размеры картинок, католог файл 0 замечаний,
 вложенность красивее сделал

2022-09-30 05:08 UTC, yunussovd commented on catalog.html
> +        <div class="footer-contacts-htmlacademy"><a class="footer-count-link" href="https://htmlacademy.ru/"><img
убрал дивы, теперт футер контакты просто список с ссылками

2022-09-30 05:17 UTC, yunussovd commented on catalog.html
> +    <meta charset="utf-8" />
а вот закрывашки, сейчас понял что они из  xhtml, и это prettier  их подкинул походу)

2022-09-30 05:18 UTC, yunussovd commented on index.html
> +          <li class="advantages-img-city"><img src="images/city.jpg" width="800" height="384"
это уже доп проверка, спишем консультацию, так как было ревью кода)

2022-09-30 05:18 UTC, yunussovd commented on index.html
> +          <li class="advantages-img-city"><img src="images/city.jpg" width="800" height="384"
отправил на доп проверку

2022-10-01 09:33 UTC, Dima-Dim requested changes
validator.w3.org/nu/ - поправить ошибки в файле index.html

2022-10-01 09:41 UTC, yunussovd commented
Все исправил, в файле 0 ошибок и варнингов

2022-10-03 08:28 UTC, yunussovd commented
> validator.w3.org/nu/ - поправить ошибки в файле index.html

Добрый день, сдано?)

2022-10-03 10:57 UTC, Dima-Dim commented
> > validator.w3.org/nu/ - поправить ошибки в файле index.html
> 
> Добрый день, сдано?)

А на проверку было отправлено? :)

2022-10-03 11:36 UTC, yunussovd commented
> 

Отправил) я думал вы просто примите этот ПР)

2022-10-03 11:40 UTC, Dima-Dim commented
> Отправил) я думал вы просто примите этот ПР)

Но принять нужно домашнее задание :)

2022-10-03 14:13 UTC, Dima-Dim commented on index.html
> +          <img class="intro-img-welcome" src="images/welcome.svg" width="187" height="44" alt="">
А тут то зачем оставил 4 изображения? Не нужно этого всего, особенно на этапе разметки.

2022-10-03 14:17 UTC, Dima-Dim commented on index.html
> +            <span>заслуживающий большего!</span>
Тут зачем `span` оставил?

2022-10-03 14:17 UTC, merged