Basic page styling
htmlacademy-htmlcss/2205907-sedona-35 pull request #4
Opened 2022-10-08 09:33 UTC by yunussovd

Adding CSS file with the suitable css rules and properties
Chaning some chtml classes names due to CSS selectors

2022-10-08 13:44 UTC, Dima-Dim requested changes
[heart-value.svg](https://github.com/htmlacademy-htmlcss/2205907-sedona-35/pull/4/files#diff-0423fa29b28c376c5b3704e08edd4ce44dd86317d8558cfb3d2a179ea9ed421e) если цифра является частью изображения, то как её менять, если значение увеличится или уменьшится.

https://htmlacademy-htmlcss.github.io/2205907-sedona-35/4/ - обрати внимание на DevTools, некоторые ресурсы не загружаются.

2022-10-08 13:44 UTC, Dima-Dim commented on catalog.html
> +          <button class="controls-button" type="button">
https://up.htmlacademy.ru/htmlcss/35/criteries#ALLY-02

2022-10-08 13:44 UTC, Dima-Dim commented on catalog.html
> +            <svg width="21" height="20" viewBox="0 0 21 20" fill="none" xmlns="http://www.w3.org/2000/svg">
Для чего в разметке это изображение?

2022-10-08 13:44 UTC, Dima-Dim commented on index.html
> +          <img class="intro-bg-img" src="images/background.jpg" width="1200" height="485" alt="">
Не должно тут быть 5 изображений. Это не оптимальный подход, например, с точки зрения загрузки ресурсов. Чего ради загружать 5 изображения, а не 2 или 3 или 4?

2022-10-08 13:44 UTC, Dima-Dim commented on index.html
> +          <h2 class="title-main">Седона — небольшой городок в Аризоне,<br>заслуживающий большего!</h2>
Почему `br`, а не ограничение ширины?

2022-10-08 13:44 UTC, Dima-Dim commented on index.html
> +        <label class="visually-hidden" for="subscribe-email"></label>
Какой смысл в пустом `label`? :)

2022-10-08 13:44 UTC, Dima-Dim commented on index.html
>            <img class="intro-devider" src="images/devider.svg" width="1200" height="57" alt="">
Это изображение является декоративным и его вообще в разметке быть не должно.

2022-10-08 13:44 UTC, Dima-Dim commented on styles/style.css
> +  height: 412px;
Если контента в этом блоке будет больше он "вывалится" из него.

2022-10-08 13:44 UTC, Dima-Dim commented on styles/style.css
> +  height: 36px;
Тоже самое произойдёт и с кнопкой, если в ней будет больше текста.

2022-10-09 16:00 UTC, yunussovd commented on catalog.html
> +          <button class="controls-button" type="button">
Готово, для скрин ридеров вещь, будет в коммите

2022-10-09 16:01 UTC, yunussovd commented on catalog.html
> +            <svg width="21" height="20" viewBox="0 0 21 20" fill="none" xmlns="http://www.w3.org/2000/svg">
В демке видел, что вставляли SVG в разметку когда верстали кнопки в навигации 
https://htmlacademy.ru/demos/93#21

2022-10-09 16:08 UTC, yunussovd commented on index.html
> +          <h2 class="title-main">Седона — небольшой городок в Аризоне,<br>заслуживающий большего!</h2>
Исправил, просто в голове <br> был самы простым решением, но не самым лучшим)

2022-10-09 16:10 UTC, yunussovd commented on index.html
> +        <label class="visually-hidden" for="subscribe-email"></label>
смысла нет)

2022-10-09 16:27 UTC, yunussovd commented on styles/style.css
> +  height: 36px;
Исправил, хоть и чутка костыльно на мой взгляд

2022-10-09 16:33 UTC, yunussovd commented on styles/style.css
> +  height: 412px;
Вот тут пока не понял, контента тут может стать больше только в виде доп фильтров если, но пока решения не нашел

2022-10-09 16:36 UTC, yunussovd commented on index.html
>            <img class="intro-devider" src="images/devider.svg" width="1200" height="57" alt="">
Фоновое которое? фоновое убрал в css

2022-10-09 16:37 UTC, yunussovd commented on index.html
> +          <img class="intro-bg-img" src="images/background.jpg" width="1200" height="485" alt="">
готово , убрал в css

2022-10-09 17:03 UTC, yunussovd commented
> [heart-value.svg](https://github.com/htmlacademy-htmlcss/2205907-sedona-35/pull/4/files#diff-0423fa29b28c376c5b3704e08edd4ce44dd86317d8558cfb3d2a179ea9ed421e) если цифра является частью изображения, то как её менять, если значение увеличится или уменьшится.
> 
> https://htmlacademy-htmlcss.github.io/2205907-sedona-35/4/ - обрати внимание на DevTools, некоторые ресурсы не загружаются.

Не знаю, пока как расположить счетчик избранного в углу сердечка, без ущерба соседним блокам и в целом именно в углу.
По загрузке оч странно, у меня все как надо грузится в Live server, странно почему в pages ссылке шрифты не подключились и внутренности хэдэра поехали, в новом апдейте, так быть не должно

2022-10-09 17:04 UTC, yunussovd commented
Если нужно открыть повторную проверку, дайте знать, пожалуйста)

2022-10-11 03:22 UTC, Dima-Dim commented on catalog.html
> +            <svg width="21" height="20" viewBox="0 0 21 20" fill="none" xmlns="http://www.w3.org/2000/svg">
На то что видел нужно накладывать и другие знания и принимать решения в соответствии с ситуацией и уметь объяснять почему ты такое решение принял.

2022-10-11 03:23 UTC, Dima-Dim commented on index.html
>            <img class="intro-devider" src="images/devider.svg" width="1200" height="57" alt="">
devider.svg которое :)

2022-10-11 03:24 UTC, Dima-Dim commented on styles/style.css
> +  height: 36px;
Точно лучше чем было.

2022-10-11 03:24 UTC, Dima-Dim commented on styles/style.css
> +  height: 412px;
Да, могу появится новые опции.

2022-10-11 03:26 UTC, Dima-Dim commented
> > [heart-value.svg](https://github.com/htmlacademy-htmlcss/2205907-sedona-35/pull/4/files#diff-0423fa29b28c376c5b3704e08edd4ce44dd86317d8558cfb3d2a179ea9ed421e) если цифра является частью изображения, то как её менять, если значение увеличится или уменьшится.
> > https://htmlacademy-htmlcss.github.io/2205907-sedona-35/4/ - обрати внимание на DevTools, некоторые ресурсы не загружаются.
> 
> Не знаю, пока как расположить счетчик избранного в углу сердечка, без ущерба соседним блокам и в целом именно в углу.

Вы пройдёте это в разделе про декоративные элементы.

> По загрузке оч странно, у меня все как надо грузится в Live server, странно почему в pages ссылке шрифты не подключились и внутренности хэдэра поехали, в новом апдейте, так быть не должно

Открыть проблемную версию в браузере и дебажить используя DevTools. У вас про них должен быть материал.

2022-10-11 03:28 UTC, Dima-Dim reviewed
Чтобы не переводить проверки, править оставшиеся проблемы в следующих заданиях.

2022-10-11 03:28 UTC, merged