#5 Flex adding
htmlacademy-htmlcss/2205907-sedona-35 pull request #5
Opened 2022-10-14 14:52 UTC by yunussovd

new blocks, classes, css attributes adding

2022-10-15 04:57 UTC, Dima-Dim requested changes

2022-10-15 04:57 UTC, Dima-Dim commented on catalog.html
> +          <a class="button-brown controls-button-form" href="catalog.html">Хочу сюда!</a>
Название `controls-button-form` было лучше чем `button-brown`. "Завтра" придёт дизайнер и решит что акцентный цвет сайта будет красный. Будешь переименовывать класс в `button-red`?

2022-10-15 04:57 UTC, Dima-Dim commented on catalog.html
> +            <button class="button-make-favorite button-blue">В избранное</button>
`button-blue` также плох как и `button-brown` :)

2022-10-15 04:57 UTC, Dima-Dim commented on styles/style.css
> +  height: 384px;
А если текста в элементе станет больше?

2022-10-15 04:57 UTC, Dima-Dim commented on styles/style.css
> +.advantages-grid2,
А если решат что элементы нужно поменять местами?

2022-10-15 04:57 UTC, Dima-Dim commented on styles/style.css
> +  height: 406px;
Тоже проблемная высота.

2022-10-15 04:57 UTC, Dima-Dim commented on styles/style.css
> +  margin-top: 20px;
На самом деле это `margin-bottom` у предыдущего элемента.

2022-10-15 04:57 UTC, Dima-Dim commented on styles/style.css
> +  height: 52px;
Из этой кнопки текст тоже начнёт выпадать, если его будет больше чем сейчас.

2022-10-15 04:57 UTC, Dima-Dim commented on styles/style.css
> +  height: 415px;
На счёт высот я думаю понятно :)

2022-10-15 04:57 UTC, Dima-Dim commented on styles/style.css
> +  margin-top: 20px;
И на счёт логики с отступами тоже.

2022-10-15 04:57 UTC, Dima-Dim commented on styles/style.css
>  .subscribe-text {
Белый текст на белом фоне?
https://up.htmlacademy.ru/htmlcss/35/criteries#ALLY-05

2022-10-15 04:57 UTC, Dima-Dim commented on styles/style.css
> +#subscribe-email {
https://up.htmlacademy.ru/htmlcss/35/criteries#CSS-04

2022-10-15 07:38 UTC, yunussovd commented on catalog.html
> +          <a class="button-brown controls-button-form" href="catalog.html">Хочу сюда!</a>
Почистил эти кнопки

2022-10-15 07:39 UTC, yunussovd commented on styles/style.css
> +  height: 384px;
Вот тут пока голову ломаю, overflow не выходб думаю

2022-10-15 08:31 UTC, yunussovd commented on styles/style.css
> +  margin-top: 20px;
Исправил

2022-10-15 08:31 UTC, yunussovd commented on styles/style.css
> +#subscribe-email {
через класс к инпуту не удалось обратиться, сделал через класс родителя и элемент инпут

2022-10-15 08:31 UTC, yunussovd commented on styles/style.css
> +.advantages-grid2,
Попробую реализовать на гридах, как и планировалось изначально, т.к. думаю это более проще и удобнее на будущее будет

2022-10-15 08:31 UTC, yunussovd commented on styles/style.css
> +.advantages-grid2,
Cделал на гридах, все круто, захотят поменять, просто 2 значения нужно будет сменить grid-columns и grid-rows

2022-10-15 08:31 UTC, yunussovd commented on styles/style.css
> +  height: 415px;
Тут, оказывается, вовсе не та картинка была, вставил нужную

2022-10-15 08:32 UTC, yunussovd commented on styles/style.css
> +  margin-top: 20px;
исправил, я их вверху все обнулил, теперь убрал из того списка и переопределил на месте

2022-10-15 08:33 UTC, yunussovd commented on styles/style.css
> +  height: 406px;
Могу сделать как футере, без задания явного значения высоты, и все паддингами сделать

2022-10-15 08:33 UTC, yunussovd commented on styles/style.css
> +  height: 52px;
Думаю, тут тоже явно не стоит задавать высоту и сделать паддинги и ширину только

2022-10-15 08:34 UTC, yunussovd commented on styles/style.css
>  .subscribe-text {
Исправил, проблема была в случае если фон не подгрузится

2022-10-17 11:07 UTC, Dima-Dim commented on styles/style.css
> +  height: 384px;
Не выход. Информация об этом должна быть у вас в материалах. Если ещё не было, оставь на будущее, но не забудь поправить.

2022-10-17 11:36 UTC, Dima-Dim requested changes
htmlacademy-htmlcss.github.io/2205907-sedona-35/5/ - решить проблему с подгрузкой шрифтов и других ресурсов которые на загружаются.

2022-10-17 11:36 UTC, Dima-Dim commented on index.html
> +            <img class="advantages-img-city" src="images/city.jpg" width="800" height="384" alt="">
НЕТ! Это изображение из  первого пункта и его нужно вернуть на место. Тоже самое сделать с изображением в конце списка.

2022-10-17 11:36 UTC, Dima-Dim commented on index.html
> +          <li class="advantages-item advantages-grid4">
Очень надёжно, но очень не универсально. Как всё это расширять, если появятся новые пункты списка? Речь про `advantages-grid4` и т.п. классы с цифрами.

2022-10-17 11:36 UTC, Dima-Dim commented on styles/style.css
> +  margin-top: 30px;
Почему не `margin-bottom` у элемента сверху? Ну и за одно зачем родителю `flex`? Обычный поток сверху вниз. Сейчас там какая-то магия, которую если разрушить, очень тяжело будет собрать обратно.

2022-10-17 11:36 UTC, Dima-Dim commented on styles/style.css
> +  font-family: 'PT Sans';
Он же от `body` наследуется.

2022-10-17 14:27 UTC, yunussovd commented on index.html
> +            <img class="advantages-img-city" src="images/city.jpg" width="800" height="384" alt="">
Как тогда быть? вы говорили вначале, что img нельзя просто так вставлять в li, я сделал с H2 , тем самым решив вопрос, как полагал, иначе если Картинка лежит в первом li, то гриды не получаются

2022-10-17 14:35 UTC, yunussovd commented on styles/style.css
> +  font-family: 'PT Sans';
Видимо не наследовался, сейчас проверил, наследуется, иначе бы не поставил)

2022-10-17 14:37 UTC, yunussovd commented on index.html
> +            <img class="advantages-img-city" src="images/city.jpg" width="800" height="384" alt="">
Могу сделать div внутри li отдельно на текст и на картинку, но выход ли

2022-10-17 14:39 UTC, yunussovd commented on index.html
> +          <li class="advantages-item advantages-grid4">
Посидел подумал, что может измениться или добавиться в эти списки, кроме иконок как в последнем ряду, где дом, бургер и еще что-то, ничего не добавить, если так будет, то можно будет просто стили последнего ряда ctrl+c ctrl+v для верхних элементов списка,

2022-10-17 14:40 UTC, yunussovd commented on index.html
> +          <li class="advantages-item advantages-grid4">
По-моему, блоки такого рода (li списка advantages) почти никогда не изменяются, а лишь изменяется текст или их меняют местами, текст изменить не проблема, поменять местами на гридах тоже проще

2022-10-17 14:42 UTC, yunussovd commented on index.html
> +          <li class="advantages-item advantages-grid4">
По названию класса, важен порядок был, поэтому именование легло таким образом, можно конечно вместо цифр добавить слова  типо: первый ряд и прочее, но тоже такое себе, на мой взгляд
Ну и так как решение гриды более удобное, то каждому элементу нужен был класс отличный от других

2022-10-17 14:43 UTC, yunussovd commented on styles/style.css
> +  margin-top: 30px;
margin-top ,так как пока что там нет полоски , которая есть в дизайне, поэтому оттолкнулся от невидимой линии, как только линия появится, можно ей задать маржин снизу, а с параграфа убрать, разумеется

2022-10-17 14:47 UTC, yunussovd commented on styles/style.css
> +  font-family: 'PT Sans';
Для кнопок шрифт, например, не наследуется

2022-10-17 15:00 UTC, yunussovd commented on index.html
> +            <img class="advantages-img-city" src="images/city.jpg" width="800" height="384" alt="">
Догоняю, почему оно должно быть именно внутри списка, потому что относится текст к картинке

2022-10-17 15:06 UTC, yunussovd commented on index.html
> +            <img class="advantages-img-city" src="images/city.jpg" width="800" height="384" alt="">
но с гридами не выйдет иначе, пробовал задать div на текст и на картинку внутри одного li, тогда display grid не работает, так как он задам к li (как и хотелось бы), а не к дивам

2022-10-17 15:13 UTC, yunussovd commented on styles/style.css
> +  margin-top: 30px;
Flex задал, так как в рядах с картинками текст центровал, и было удобно сделать текст по горизонтальной оси в середине картинки

2022-10-17 15:43 UTC, yunussovd commented on index.html
> +            <img class="advantages-img-city" src="images/city.jpg" width="800" height="384" alt="">
Сейчас залью решение с Advantages на флексах и картинками внутри li , но думаю, теперь сложнее это поддерживать или просто гриды в данном случае мне больше импонируют, но в гридах увы картинку внутрь li не вставишь

2022-10-17 15:49 UTC, yunussovd commented on styles/style.css
> +  height: 384px;
по-хорошему padding должен давать пространство для текста, но при этом с большим текстом размер  блока не должен быть больше 384px, что и является высотой картинок в секции, иначе будет не красиво, поэтому задач высоту, либо можно задать max-height

2022-10-19 02:55 UTC, Dima-Dim commented on index.html
> +            <img class="advantages-img-city" src="images/city.jpg" width="800" height="384" alt="">
> в гридах увы картинку внутрь li не вставишь

Это почему? :)

2022-10-19 02:56 UTC, Dima-Dim commented on styles/style.css
> +  font-family: 'PT Sans';
Но тут и во многих других места не кнопка :)

2022-10-19 02:58 UTC, Dima-Dim commented on index.html
> +          <li class="advantages-item advantages-grid4">
> лишь изменяется текст.

Пробовал добавить текста раз в 5 или 7 больше имеющегося?

2022-10-19 03:03 UTC, Dima-Dim commented on index.html
> +          <li class="advantages-item advantages-grid4">
Для стилизации элемента по позиции есть https://developer.mozilla.org/ru/docs/Web/CSS/:nth-child и на эту теме есть тренажёры. В остальных случаях, речь обычно про назначении элемента, например, `advantage-item--house`, или `advantage-item--with-image`.

2022-10-19 03:48 UTC, Dima-Dim commented on styles/style.css
> +  height: 384px;
Красиво это хорошо, но красиво и текст который либо "вывалился", либо скрылся и стал не доступным это не красиво.

2022-10-19 04:24 UTC, yunussovd commented on index.html
> +            <img class="advantages-img-city" src="images/city.jpg" width="800" height="384" alt="">
Вы сами так сказали, в первой реализации на гридах так и было) может вы имели ввиду чтобы я убрал картинки, так как тогда сдавал только разметку, но я понял это как убрать картинку из отдельного li и поместить ее в li с подходящим текстом)_

2022-10-19 04:27 UTC, yunussovd commented on index.html
> +          <li class="advantages-item advantages-grid4">
Пробовал, текст прячется под нижний блок advantages

> > лишь изменяется текст.
> 
> Пробовал добавить текста раз в 5 или 7 больше имеющегося?

2022-10-19 04:35 UTC, yunussovd commented on index.html
> +          <li class="advantages-item advantages-grid4">
Закрыл проблему переполнения блоков  Adavantages, но возник в них другой вопрос контроля высото до требуемой, но решу ее , когда добавлю горизонтальный слэш между тайтлом и параграфом

2022-10-19 05:19 UTC, yunussovd commented on index.html
> +          <li class="advantages-item advantages-grid4">
> Для стилизации элемента по позиции есть https://developer.mozilla.org/ru/docs/Web/CSS/:nth-child и на эту теме есть тренажёры. В остальных случаях, речь обычно про назначении элемента, например, `advantage-item--house`, или `advantage-item--with-image`.

Готово

2022-10-19 05:25 UTC, yunussovd commented on index.html
> +            <img class="advantages-img-city" src="images/city.jpg" width="800" height="384" alt="">
Ладно, сейчас реализация на флексах блока advantages , в целом меня устраивает ) легкость поддержки секции на  7, думаю)

2022-10-19 15:51 UTC, yunussovd commented
https://htmlacademy-htmlcss.github.io/2205907-sedona-35/5/
Почему это выглядит так убого, не знаете? ни шрифты, ни картинки не подгружены, вроде все в одном месте, в репозитории, но чего-то не хватает

2022-10-19 15:53 UTC, Dima-Dim commented on index.html
> +            <img class="advantages-icon" src="/images/icon-house.svg" width="75" height="72" alt="">
Это декоративные изображения и в разметке их быть не должно.

2022-10-19 15:53 UTC, merged

2022-10-19 15:57 UTC, Dima-Dim commented
> https://htmlacademy-htmlcss.github.io/2205907-sedona-35/5/ Почему это выглядит так убого, не знаете? ни шрифты, ни картинки не подгружены, вроде все в одном месте, в репозитории, но чего-то не хватает

Знаю, но это мой вопрос к тебе, на предмет использования DevTools.

2022-10-19 16:10 UTC, yunussovd commented on styles/style.css
> +  height: 384px;
Кстати, пофиксил, еще в обед

2022-10-19 16:13 UTC, yunussovd commented on index.html
> +            <img class="advantages-icon" src="/images/icon-house.svg" width="75" height="72" alt="">
> > https://htmlacademy-htmlcss.github.io/2205907-sedona-35/5/ Почему это выглядит так убого, не знаете? ни шрифты, ни картинки не подгружены, вроде все в одном месте, в репозитории, но чего-то не хватает
> 
> Знаю, но это мой вопрос к тебе, на предмет использования DevTools.

![image](https://user-images.githubusercontent.com/72697879/196746518-50ead1f2-f113-4dbf-b354-fb2c4f03732f.png)
вижу в нетворках, что они просто не подгружаются, есть идея

2022-10-19 16:23 UTC, yunussovd commented
> > https://htmlacademy-htmlcss.github.io/2205907-sedona-35/5/ Почему это выглядит так убого, не знаете? ни шрифты, ни картинки не подгружены, вроде все в одном месте, в репозитории, но чего-то не хватает
> 
> Знаю, но это мой вопрос к тебе, на предмет использования DevTools.

Ответ, относительные пути к ресурсам, изменил чутка путь, должно работать как надо

2022-10-19 16:36 UTC, yunussovd commented on index.html
> +            <img class="advantages-icon" src="/images/icon-house.svg" width="75" height="72" alt="">
> Это декоративные изображения и в разметке их быть не должно.

Исправил)