Pixel perfect + footer pseudoclasses update
htmlacademy-htmlcss/2205907-sedona-35 pull request #7
Opened 2022-10-24 15:21 UTC by yunussovd

Pixel perfect marks and foorter pseudoclasses was added

2022-10-25 07:19 UTC, Dima-Dim requested changes
Давай ты всё же проверишь то что поучилось валидатором :) validator.w3.org/nu/

2022-10-25 14:52 UTC, yunussovd commented
Валидатор прошел, все апрувното

2022-10-25 17:46 UTC, yunussovd commented
Cделал счетчик отелей в избранном) пришлось изощриться и подсмотреть кое-где

2022-10-26 07:55 UTC, Dima-Dim requested changes

2022-10-26 07:55 UTC, Dima-Dim commented on catalog.html
> +              <div class="favorite-block" aria-label="Избранное, 12 в избранном">
Не перебор ли тут с 3-мя тегами вложенными?

2022-10-26 07:55 UTC, Dima-Dim commented on styles/style.css
> +.button--listshow:active {
Когда видишь такие конструкции возникает вопрос, а нельзя всё это в класс `button`, который будет использовать везде, где необходимо подобное поведение?

2022-10-26 12:32 UTC, yunussovd commented on catalog.html
> +              <div class="favorite-block" aria-label="Избранное, 12 в избранном">
да, один спан там бесполезный

2022-10-26 12:33 UTC, yunussovd commented on styles/style.css
> +.button--listshow:active {
Можно, но тогда всем кнопкам класс нужно будет дописать универсальный

2022-10-26 12:37 UTC, Dima-Dim commented on styles/style.css
> +.button--listshow:active {
И это нормально и удобно.

2022-10-26 12:37 UTC, yunussovd commented on styles/style.css
> +.button--listshow:active {
Но кстати, вообще идеально было бы именовать из по БЭМу, с названием модификатора в конце чтобы поще ориентироваться, так как есть кнопки голубые , а есть кнопки коричневые и прозрачная, поэтому реализовал именно так, сгруппировав их
а вот к похожим местам можно добавить один общий класс

2022-10-26 12:38 UTC, yunussovd commented on styles/style.css
> +.button--listshow:active {
Сделаю иначе, дам класс кнопка-голубая, кнопка коричневая) как и было когда-то )

2022-10-26 13:41 UTC, Dima-Dim commented on styles/style.css
> +.button--listshow:active {
> дам класс кнопка-голубая

Не рекомендовал бы привязываться к тому, как это выглядит. Когда я об этом уже писал :)

2022-10-26 14:30 UTC, yunussovd commented
я что-то голову сломал чутка как в хлебные крошки вставить стрелку, так и не вышло, потом еще подумаю

2022-10-26 14:32 UTC, Dima-Dim commented
> я что-то голову сломал чутка как в хлебные крошки вставить стрелку, так и не вышло, потом еще подумаю

Пока убрать и вернуться к этом после раздела про Декоративные элементы.

2022-10-26 14:32 UTC, yunussovd commented on styles/style.css
> +.button--listshow:active {
Это ведь только для псевдоклассов, универсальный на все не придумаешь, когда есть кнопка коричневая со своими состояниями голубая

2022-10-26 14:34 UTC, yunussovd commented
> > я что-то голову сломал чутка как в хлебные крошки вставить стрелку, так и не вышло, потом еще подумаю
> 
> Пока убрать и вернуться к этом после раздела про Декоративные элементы.

визуально все равно ничего не изменилось. могу закомментировать и снова закоммитить

2022-10-27 05:12 UTC, Dima-Dim requested changes
[images/icons/advantages-item--stroke-dark.svg](https://github.com/htmlacademy-htmlcss/2205907-sedona-35/pull/7/files#diff-06e728b288abdc5e4ead334ddf4c007c457597efef0546281e9a6bee5173e63f) - что это?

2022-10-27 05:12 UTC, Dima-Dim commented on styles/style.css
> +  margin: -8px 0 0 9px;
Если элемент позиционирова абсолютно, то для его постановки на место сеществуют такие свойства как `top`, `left`, `bottom` и `right`.

2022-10-27 08:37 UTC, yunussovd commented
> [images/icons/advantages-item--stroke-dark.svg](https://github.com/htmlacademy-htmlcss/2205907-sedona-35/pull/7/files#diff-06e728b288abdc5e4ead334ddf4c007c457597efef0546281e9a6bee5173e63f) - что это?

Это в разделе advantages строчка между тайтлом и текстом, есть светлая на синих квадратах и темная линия на светлых квадратах

2022-10-27 08:41 UTC, Dima-Dim commented
> Это в разделе advantages строчка между тайтлом и текстом, есть светлая на синих квадратах и темная линия на светлых квадратах

Ммм, теперь увидел :) спасибо! Но всё равно, зачем для этого svg?

2022-10-27 08:45 UTC, yunussovd commented
можно было и пнг, но все мелочи в свг выгружал, вдруг кому-то захочется увеличить блок и проверить сохраняет ли эта линия свое качество)

2022-10-27 08:50 UTC, Dima-Dim commented
> можно было и пнг, но все мелочи в свг выгружал, вдруг кому-то захочется увеличить блок и проверить сохраняет ли эта линия свое качество)

Тогда давай вернёмся к этому вопросу после раздела про Декоративные элементы.

2022-10-27 09:27 UTC, yunussovd commented
> > можно было и пнг, но все мелочи в свг выгружал, вдруг кому-то захочется увеличить блок и проверить сохраняет ли эта линия свое качество)
> 
> Тогда давай вернёмся к этому вопросу после раздела про Декоративные элементы.

Да, без проблем, убрать или пока норм и пусть будет и не мешает?

2022-10-27 09:35 UTC, Dima-Dim commented
> Да, без проблем, убрать или пока норм и пусть будет и не мешает?

Убрать.

2022-10-27 09:39 UTC, yunussovd commented
> > Да, без проблем, убрать или пока норм и пусть будет и не мешает?
> 
> Убрать.

Done

2022-10-27 12:11 UTC, yunussovd commented on styles/style.css
> +  margin: -8px 0 0 9px;
Исправил, да я до этого так и пробовал, но меня паддинг (сейчас понял) не пускал, поэтому психанул и марджин сделал)

2022-10-28 08:41 UTC, merged