#9 modal window
htmlacademy-htmlcss/2205907-sedona-35 pull request #9
Opened 2022-11-07 13:48 UTC by yunussovd

2022-11-07 15:09 UTC, Dima-Dim requested changes

2022-11-07 15:09 UTC, Dima-Dim commented on index.html
> +                <div class="choseen-number-result">
Т.е. руками цифру ввести нельзя? :) Это не очень хорошо. У тебя же есть `label` значит что и `input` быть тоже должен.

2022-11-07 15:09 UTC, Dima-Dim commented on index.html
> +                <div class="number-reduce-button">
Судя по классу ты понимаешь что это интерактивный элемент, но делаешь его `div`-ом.

2022-11-07 15:09 UTC, Dima-Dim commented on index.html
> +              <button class="search-form-button">
А чего тип не `submit`?

2022-11-07 15:09 UTC, Dima-Dim commented on styles/style.css
> +  position: absolute;
Зачем он в `absolute`? Вроде вполне может быть и в потоке.

2022-11-07 15:09 UTC, Dima-Dim commented on styles/style.css
> +  position: absolute;
Тоже не понятно для чего `absolute` более того, с учётом того что в нём текст это ещё и опасно в плане переполнения.

2022-11-07 15:09 UTC, Dima-Dim commented on styles/style.css
> +  position: absolute;
Ну нет :) не так же это делается :) Не нашёл это в демках. Раньше было, сейчас не вижу. Но суть в следующем, если нативный input стилизовать как нужно не получается, то он просто скрывается с помощью `visually_hidden`.

2022-11-07 15:28 UTC, yunussovd commented on index.html
> +                <div class="choseen-number-result">
теперь можно, все в порядке) я даже значения макс и мин выставил

2022-11-07 15:28 UTC, yunussovd commented on index.html
> +                <div class="number-reduce-button">
Исправил на кнопку

2022-11-07 15:30 UTC, yunussovd commented on index.html
> +              <button class="search-form-button">
Точно , забыл последней кнопке тип дать , исправил

2022-11-07 15:30 UTC, yunussovd commented on styles/style.css
> +  position: absolute;
чтобы было поверх других элементов

2022-11-07 15:31 UTC, yunussovd commented on styles/style.css
> +  position: absolute;
Ну вот да, тоже костыльно и этот вопрос вам в тг тоже задавал, о том как быть с изменением текста, вырезать его из потока или оставить, ведь могут быть ситуации , когда этого текста вовсе не будет

2022-11-07 15:47 UTC, yunussovd commented on styles/style.css
> +  position: absolute;
Попробовал, прикольно, функционал не потерял вообще, зато куском кода в css меньше

2022-11-08 13:50 UTC, Dima-Dim commented on styles/style.css
> +  position: absolute;
Попробуй оставить его в потоке.

2022-11-08 13:52 UTC, Dima-Dim commented on styles/style.css
> +  position: absolute;
Тексты должны быть в потоке, иначе они могут наложиться на соседние элементы.

2022-11-08 16:20 UTC, yunussovd commented on styles/style.css
> +  position: absolute;
Убрал, но без текста, будут сплюснуты инпуты, можно исправить  добавление гридам строк, так как сейчас я задал лишь столбцы, либо уже позже в js развиваить тему и контролировать место

2022-11-08 16:30 UTC, yunussovd commented on styles/style.css
> +  position: absolute;
Закрыл проблему отсутствия текста под полем даты, добавив gap  строчный

2022-11-08 19:03 UTC, yunussovd commented on styles/style.css
> +  position: absolute;
оставил

2022-11-09 14:33 UTC, Dima-Dim requested changes

2022-11-09 14:33 UTC, Dima-Dim commented on index.html
> +        <section class="modal-content">
Там себе section если в ней только заголовок и ничего больше.

2022-11-09 14:33 UTC, Dima-Dim commented on index.html
> +              <span class="date-button--check-in">
Почему span?

2022-11-09 14:33 UTC, Dima-Dim commented on index.html
> +                <button class="number-reduce-button">
https://up.htmlacademy.ru/htmlcss/35/criteries#ALLY-02

2022-11-09 14:33 UTC, Dima-Dim commented on index.html
> +                <label class="number-of-people--lable" for="kids">Дети:</label>
Где связь с `input`-ом?

2022-11-09 14:33 UTC, Dima-Dim commented on index.html
> +              <span class="number-of-people--lable">
Раз уж там внутри так много всего, то может `p`?

2022-11-09 15:41 UTC, yunussovd commented on index.html
> +              <span class="date-button--check-in">
Просто решил спаном вставить свг, чтобы самому свг не добавлять класс, можно было и див, но в данном случае, разницы нет

2022-11-09 15:48 UTC, yunussovd commented on index.html
> +                <button class="number-reduce-button">
я так понимаю, добавить блоку текст для скринридеров

2022-11-09 15:52 UTC, yunussovd commented on index.html
> +                <label class="number-of-people--lable" for="kids">Дети:</label>
исправил

2022-11-09 15:53 UTC, yunussovd commented on index.html
> +              <span class="number-of-people--lable">
вместо span просто p?

2022-11-09 15:58 UTC, yunussovd commented on index.html
> +              <span class="number-of-people--lable">
cделал

2022-11-10 13:33 UTC, Dima-Dim commented on index.html
> +              <span class="date-button--check-in">
Если бы разницы не было :) я бы не спрашивал. Ведь это не просто иконка, это интерактивный элемент.

2022-11-10 13:34 UTC, Dima-Dim commented on index.html
> +                <button class="number-reduce-button">
Не блоку, а интерактивному элементу, которым, в данном случае, является кнопка.

2022-11-10 13:34 UTC, Dima-Dim commented on index.html
> +              <span class="number-of-people--lable">
Ага.

2022-11-10 15:43 UTC, yunussovd commented on index.html
> +              <span class="date-button--check-in">
аа, кнопка , а сделал тупо через спан и курсор поинтер))

2022-11-10 15:44 UTC, yunussovd commented on index.html
> +                <button class="number-reduce-button">
ну да, так  и сделал

2022-11-10 15:54 UTC, yunussovd commented
Все исправил

2022-11-12 07:35 UTC, Dima-Dim commented on index.html
> +              <button class="date-button--check-in">
https://up.htmlacademy.ru/htmlcss/35/criteries#ALLY-02

2022-11-12 07:35 UTC, merged

2022-11-12 08:27 UTC, yunussovd commented on index.html
> +              <button class="date-button--check-in">
Добавил спан скрытый с описанием кнопки выбора даты